# Generated by Django 4.2.11 on 2024-05-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
